### ISSUE TITLE
Need help regarding Yolov5 Architecture

### ISSUE THREAD

**Issue by abh1sh5k** [positive666/Deepstream_Project#3]
I was working on fish detection and tracking system in 3 dimensions using MS Kinect, and used yolov5s for rgb frames. I wanted to experiment a bit with the architecture
of yolov5, but as a beginner i am struggling to find the relation between the arguments in the classes used in common.py and the arguments used in yaml 
file in the ultralytics repo.

PS : If you can add in some resources from where i can learn about the architecture and layers, then it would really help. Thank you !

**Comment by positive666** [comment]
So you mean you need to train your own data set model under torch's yolov5? This project is only model conversion and deepstream migration. Do you need yolov5 source code training?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "positive666/Deepstream_Project"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 晚上7:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[positive666/Deepstream_Project] Need help regarding Yolov5 Architecture (#3)





 
I was working on fish detection and tracking system in 3 dimensions using MS Kinect, and used yolov5s for rgb frames. I wanted to experiment a bit with the architecture
 of yolov5, but as a beginner i am struggling to find the relation between the arguments in the classes used in common.py and the arguments used in yaml
 file in the ultralytics repo.
 
PS : If you can add in some resources from where i can learn about the architecture and layers, then it would really help. Thank you !

**Comment by abh1sh5k** [comment]
@positive666 I want to add some layers in the yolov5s.yaml file. But I could not understand the arguments to be passed in that layer.

**Comment by positive666** [comment]
hi, I did modify the structure on the fork's V5 REPO, you can refer to mine to see? The main change is to add class functions to commo.py, then register in yolo.py, and finally modify in yaml, and debug through python model.py




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Abhishek ***@***.***&gt;; 
发送时间: 2021年5月12日(星期三) 晚上6:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [positive666/Deepstream_Project] Need help regarding Yolov5 Architecture (#3)





 
@positive666 I want to add some layers in the yolov5s.yaml file. But I could not understand the arguments to be passed in that layer.

**Comment by abh1sh5k** [comment]
Ok Thanks... Got it...
